// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR3-WOGY7TAj74fOz38oDNiY035Cjm7ec',
    appId: '1:646901701952:web:e12cf1f09d74e13e90aea5',
    messagingSenderId: '646901701952',
    projectId: 'tyamo-app-263ac',
    authDomain: 'tyamo-app-263ac.firebaseapp.com',
    storageBucket: 'tyamo-app-263ac.appspot.com',
    measurementId: 'G-DPNY6GBJ5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkJroCLx50sWILZU_brHzxpf7sd4SSJk',
    appId: '1:646901701952:android:6fe2c010d577479190aea5',
    messagingSenderId: '646901701952',
    projectId: 'tyamo-app-263ac',
    storageBucket: 'tyamo-app-263ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWzxv1LEvWej3obWMOGZpEg8co4AaOHF4',
    appId: '1:646901701952:ios:4f770b56d3438aed90aea5',
    messagingSenderId: '646901701952',
    projectId: 'tyamo-app-263ac',
    storageBucket: 'tyamo-app-263ac.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWzxv1LEvWej3obWMOGZpEg8co4AaOHF4',
    appId: '1:646901701952:ios:4f770b56d3438aed90aea5',
    messagingSenderId: '646901701952',
    projectId: 'tyamo-app-263ac',
    storageBucket: 'tyamo-app-263ac.appspot.com',
    iosBundleId: 'com.example.tyamo',
  );
}
